#############################################################################
# Makefile for building: RavensbourneTable.app/Contents/MacOS/RavensbourneTable
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  RavensbourneTable.pro
# Template: app
# Command: /Users/jons/Qt/5.8/ios/bin/qmake -o project.pbxproj RavensbourneTable.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/jons/Qt/5.8/ios/bin/qmake
project.pbxproj: RavensbourneTable.pro ../../../../Qt/5.8/ios/mkspecs/macx-ios-clang/qmake.conf ../../../../Qt/5.8/ios/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.8/ios/mkspecs/qdevice.pri \
		../../../../Qt/5.8/ios/mkspecs/features/device_config.prf \
		../../../../Qt/5.8/ios/mkspecs/common/unix.conf \
		../../../../Qt/5.8/ios/mkspecs/common/mac.conf \
		../../../../Qt/5.8/ios/mkspecs/common/uikit.conf \
		../../../../Qt/5.8/ios/mkspecs/common/ios.conf \
		../../../../Qt/5.8/ios/mkspecs/common/sanitize.conf \
		../../../../Qt/5.8/ios/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.8/ios/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.8/ios/mkspecs/common/clang.conf \
		../../../../Qt/5.8/ios/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.8/ios/mkspecs/common/ios/clang.conf \
		../../../../Qt/5.8/ios/mkspecs/common/ios/qmake.conf \
		../../../../Qt/5.8/ios/mkspecs/qconfig.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_gltfsceneio.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qgif.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qicns.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qico.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qios.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtga.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		../../../../Qt/5.8/ios/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.8/ios/mkspecs/features/qt_config.prf \
		../../../../Qt/5.8/ios/mkspecs/features/uikit/qt_config.prf \
		../../../../Qt/5.8/ios/mkspecs/macx-ios-clang/qmake.conf \
		../../../../Qt/5.8/ios/mkspecs/macx-xcode/qmake.conf \
		../../../../Qt/5.8/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.8/ios/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.8/ios/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.8/ios/mkspecs/features/uikit/sdk.prf \
		../../../../Qt/5.8/ios/mkspecs/features/toolchain.prf \
		../../../../Qt/5.8/ios/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/5.8/ios/mkspecs/features/default_pre.prf \
		../../../../Qt/5.8/ios/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.8/ios/mkspecs/features/uikit/default_pre.prf \
		../../../../Qt/5.8/ios/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.8/ios/mkspecs/features/uikit/resolve_config.prf \
		../../../../Qt/5.8/ios/mkspecs/features/default_post.prf \
		../../../../Qt/5.8/ios/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.8/ios/mkspecs/features/uikit/default_post.prf \
		../../../../Qt/5.8/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		../../../../Qt/5.8/ios/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.8/ios/mkspecs/features/uikit/bitcode.prf \
		../../../../Qt/5.8/ios/mkspecs/features/warn_on.prf \
		../../../../Qt/5.8/ios/plugins/platforms/libqios_debug.prl \
		../../../../Qt/5.8/ios/mkspecs/features/qt.prf \
		../../../../Qt/5.8/ios/mkspecs/features/uikit/qt.prf \
		../../../../Qt/5.8/ios/mkspecs/features/resources.prf \
		../../../../Qt/5.8/ios/mkspecs/features/moc.prf \
		../../../../Qt/5.8/ios/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.8/ios/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.8/ios/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.8/ios/mkspecs/features/file_copies.prf \
		../../../../Qt/5.8/ios/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.8/ios/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/5.8/ios/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.8/ios/mkspecs/features/uikit/testcase_targets.prf \
		../../../../Qt/5.8/ios/mkspecs/features/exceptions.prf \
		../../../../Qt/5.8/ios/mkspecs/features/yacc.prf \
		../../../../Qt/5.8/ios/mkspecs/features/lex.prf \
		RavensbourneTable.pro \
		../../../../Qt/5.8/ios/mkspecs/macx-ios-clang/Default-568h@2x.png \
		../../../../Qt/5.8/ios/mkspecs/macx-ios-clang/LaunchScreen.xib \
		qml.qrc \
		../../../../Qt/5.8/ios/lib/libQt5FontDatabaseSupport_debug.prl \
		../../../../Qt/5.8/ios/lib/libQt5GraphicsSupport_debug.prl \
		../../../../Qt/5.8/ios/lib/libQt5ClipboardSupport_debug.prl \
		../../../../Qt/5.8/ios/lib/libQt5Gui_debug.prl \
		../../../../Qt/5.8/ios/lib/libqtharfbuzz_debug.prl \
		../../../../Qt/5.8/ios/lib/libQt5Core_debug.prl \
		../../../../Qt/5.8/ios/lib/libqtpcre_debug.prl \
		../../../../Qt/5.8/ios/lib/libqtfreetype_debug.prl \
		../../../../Qt/5.8/ios/lib/libqtlibpng_debug.prl \
		../../../../Qt/5.8/ios/lib/libQt5Quick_debug.prl \
		../../../../Qt/5.8/ios/lib/libQt5Qml_debug.prl \
		../../../../Qt/5.8/ios/lib/libQt5Network_debug.prl \
		../../../../Qt/5.8/ios/qml/QtQuick.2/libqtquick2plugin_debug.prl \
		../../../../Qt/5.8/ios/qml/QtQuick/Controls.2/libqtquickcontrols2plugin_debug.prl \
		../../../../Qt/5.8/ios/qml/QtQuick/Templates.2/libqtquicktemplates2plugin_debug.prl \
		../../../../Qt/5.8/ios/qml/QtQuick/Window.2/libwindowplugin_debug.prl \
		../../../../Qt/5.8/ios/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin_debug.prl \
		../../../../Qt/5.8/ios/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate_debug.prl \
		../../../../Qt/5.8/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin_debug.prl \
		../../../../Qt/5.8/ios/qml/QtWebView/libdeclarative_webview_debug.prl \
		../../../../Qt/5.8/ios/qml/QtQuick/Dialogs/libdialogplugin_debug.prl \
		../../../../Qt/5.8/ios/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin_debug.prl \
		../../../../Qt/5.8/ios/qml/Qt/labs/settings/libqmlsettingsplugin_debug.prl \
		../../../../Qt/5.8/ios/qml/QtQuick/Dialogs/Private/libdialogsprivateplugin_debug.prl \
		../../../../Qt/5.8/ios/qml/QtQuick/Controls/libqtquickcontrolsplugin_debug.prl \
		../../../../Qt/5.8/ios/qml/QtQuick/PrivateWidgets/libwidgetsplugin_debug.prl \
		../../../../Qt/5.8/ios/plugins/imageformats/libqgif_debug.prl \
		../../../../Qt/5.8/ios/plugins/imageformats/libqicns_debug.prl \
		../../../../Qt/5.8/ios/plugins/imageformats/libqico_debug.prl \
		../../../../Qt/5.8/ios/plugins/imageformats/libqjpeg_debug.prl \
		../../../../Qt/5.8/ios/plugins/imageformats/libqmacjp2_debug.prl \
		../../../../Qt/5.8/ios/plugins/imageformats/libqtga_debug.prl \
		../../../../Qt/5.8/ios/plugins/imageformats/libqtiff_debug.prl \
		../../../../Qt/5.8/ios/plugins/imageformats/libqwbmp_debug.prl \
		../../../../Qt/5.8/ios/plugins/imageformats/libqwebp_debug.prl \
		../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_debugger_debug.prl \
		../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_inspector_debug.prl \
		../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_local_debug.prl \
		../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_native_debug.prl \
		../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_profiler_debug.prl \
		../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_quickprofiler_debug.prl \
		../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_server_debug.prl \
		../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_tcp_debug.prl \
		../../../../Qt/5.8/ios/plugins/bearer/libqgenericbearer_debug.prl
	$(QMAKE) -o project.pbxproj RavensbourneTable.pro -spec macx-xcode
../../../../Qt/5.8/ios/mkspecs/features/spec_pre.prf:
../../../../Qt/5.8/ios/mkspecs/qdevice.pri:
../../../../Qt/5.8/ios/mkspecs/features/device_config.prf:
../../../../Qt/5.8/ios/mkspecs/common/unix.conf:
../../../../Qt/5.8/ios/mkspecs/common/mac.conf:
../../../../Qt/5.8/ios/mkspecs/common/uikit.conf:
../../../../Qt/5.8/ios/mkspecs/common/ios.conf:
../../../../Qt/5.8/ios/mkspecs/common/sanitize.conf:
../../../../Qt/5.8/ios/mkspecs/common/gcc-base.conf:
../../../../Qt/5.8/ios/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.8/ios/mkspecs/common/clang.conf:
../../../../Qt/5.8/ios/mkspecs/common/clang-mac.conf:
../../../../Qt/5.8/ios/mkspecs/common/ios/clang.conf:
../../../../Qt/5.8/ios/mkspecs/common/ios/qmake.conf:
../../../../Qt/5.8/ios/mkspecs/qconfig.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_lib_zlib_private.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_gltfsceneio.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qgif.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qicns.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qico.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qios.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qjpeg.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmacjp2.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qminimal.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsvg.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtga.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtiff.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
../../../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qwebp.pri:
../../../../Qt/5.8/ios/mkspecs/features/qt_functions.prf:
../../../../Qt/5.8/ios/mkspecs/features/qt_config.prf:
../../../../Qt/5.8/ios/mkspecs/features/uikit/qt_config.prf:
../../../../Qt/5.8/ios/mkspecs/macx-ios-clang/qmake.conf:
../../../../Qt/5.8/ios/mkspecs/macx-xcode/qmake.conf:
../../../../Qt/5.8/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.8/ios/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.8/ios/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.8/ios/mkspecs/features/uikit/sdk.prf:
../../../../Qt/5.8/ios/mkspecs/features/toolchain.prf:
../../../../Qt/5.8/ios/mkspecs/features/mac/toolchain.prf:
../../../../Qt/5.8/ios/mkspecs/features/default_pre.prf:
../../../../Qt/5.8/ios/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.8/ios/mkspecs/features/uikit/default_pre.prf:
../../../../Qt/5.8/ios/mkspecs/features/resolve_config.prf:
../../../../Qt/5.8/ios/mkspecs/features/uikit/resolve_config.prf:
../../../../Qt/5.8/ios/mkspecs/features/default_post.prf:
../../../../Qt/5.8/ios/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.8/ios/mkspecs/features/uikit/default_post.prf:
../../../../Qt/5.8/ios/mkspecs/macx-ios-clang/features/default_post.prf:
../../../../Qt/5.8/ios/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.8/ios/mkspecs/features/uikit/bitcode.prf:
../../../../Qt/5.8/ios/mkspecs/features/warn_on.prf:
../../../../Qt/5.8/ios/plugins/platforms/libqios_debug.prl:
../../../../Qt/5.8/ios/mkspecs/features/qt.prf:
../../../../Qt/5.8/ios/mkspecs/features/uikit/qt.prf:
../../../../Qt/5.8/ios/mkspecs/features/resources.prf:
../../../../Qt/5.8/ios/mkspecs/features/moc.prf:
../../../../Qt/5.8/ios/mkspecs/features/unix/opengl.prf:
../../../../Qt/5.8/ios/mkspecs/features/unix/thread.prf:
../../../../Qt/5.8/ios/mkspecs/features/qmake_use.prf:
../../../../Qt/5.8/ios/mkspecs/features/file_copies.prf:
../../../../Qt/5.8/ios/mkspecs/features/mac/rez.prf:
../../../../Qt/5.8/ios/mkspecs/features/mac/asset_catalogs.prf:
../../../../Qt/5.8/ios/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.8/ios/mkspecs/features/uikit/testcase_targets.prf:
../../../../Qt/5.8/ios/mkspecs/features/exceptions.prf:
../../../../Qt/5.8/ios/mkspecs/features/yacc.prf:
../../../../Qt/5.8/ios/mkspecs/features/lex.prf:
RavensbourneTable.pro:
../../../../Qt/5.8/ios/mkspecs/macx-ios-clang/Default-568h@2x.png:
../../../../Qt/5.8/ios/mkspecs/macx-ios-clang/LaunchScreen.xib:
qml.qrc:
../../../../Qt/5.8/ios/lib/libQt5FontDatabaseSupport_debug.prl:
../../../../Qt/5.8/ios/lib/libQt5GraphicsSupport_debug.prl:
../../../../Qt/5.8/ios/lib/libQt5ClipboardSupport_debug.prl:
../../../../Qt/5.8/ios/lib/libQt5Gui_debug.prl:
../../../../Qt/5.8/ios/lib/libqtharfbuzz_debug.prl:
../../../../Qt/5.8/ios/lib/libQt5Core_debug.prl:
../../../../Qt/5.8/ios/lib/libqtpcre_debug.prl:
../../../../Qt/5.8/ios/lib/libqtfreetype_debug.prl:
../../../../Qt/5.8/ios/lib/libqtlibpng_debug.prl:
../../../../Qt/5.8/ios/lib/libQt5Quick_debug.prl:
../../../../Qt/5.8/ios/lib/libQt5Qml_debug.prl:
../../../../Qt/5.8/ios/lib/libQt5Network_debug.prl:
../../../../Qt/5.8/ios/qml/QtQuick.2/libqtquick2plugin_debug.prl:
../../../../Qt/5.8/ios/qml/QtQuick/Controls.2/libqtquickcontrols2plugin_debug.prl:
../../../../Qt/5.8/ios/qml/QtQuick/Templates.2/libqtquicktemplates2plugin_debug.prl:
../../../../Qt/5.8/ios/qml/QtQuick/Window.2/libwindowplugin_debug.prl:
../../../../Qt/5.8/ios/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin_debug.prl:
../../../../Qt/5.8/ios/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate_debug.prl:
../../../../Qt/5.8/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin_debug.prl:
../../../../Qt/5.8/ios/qml/QtWebView/libdeclarative_webview_debug.prl:
../../../../Qt/5.8/ios/qml/QtQuick/Dialogs/libdialogplugin_debug.prl:
../../../../Qt/5.8/ios/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin_debug.prl:
../../../../Qt/5.8/ios/qml/Qt/labs/settings/libqmlsettingsplugin_debug.prl:
../../../../Qt/5.8/ios/qml/QtQuick/Dialogs/Private/libdialogsprivateplugin_debug.prl:
../../../../Qt/5.8/ios/qml/QtQuick/Controls/libqtquickcontrolsplugin_debug.prl:
../../../../Qt/5.8/ios/qml/QtQuick/PrivateWidgets/libwidgetsplugin_debug.prl:
../../../../Qt/5.8/ios/plugins/imageformats/libqgif_debug.prl:
../../../../Qt/5.8/ios/plugins/imageformats/libqicns_debug.prl:
../../../../Qt/5.8/ios/plugins/imageformats/libqico_debug.prl:
../../../../Qt/5.8/ios/plugins/imageformats/libqjpeg_debug.prl:
../../../../Qt/5.8/ios/plugins/imageformats/libqmacjp2_debug.prl:
../../../../Qt/5.8/ios/plugins/imageformats/libqtga_debug.prl:
../../../../Qt/5.8/ios/plugins/imageformats/libqtiff_debug.prl:
../../../../Qt/5.8/ios/plugins/imageformats/libqwbmp_debug.prl:
../../../../Qt/5.8/ios/plugins/imageformats/libqwebp_debug.prl:
../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_debugger_debug.prl:
../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_inspector_debug.prl:
../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_local_debug.prl:
../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_native_debug.prl:
../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_profiler_debug.prl:
../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_quickprofiler_debug.prl:
../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_server_debug.prl:
../../../../Qt/5.8/ios/plugins/qmltooling/libqmldbg_tcp_debug.prl:
../../../../Qt/5.8/ios/plugins/bearer/libqgenericbearer_debug.prl:
qmake: FORCE
	@$(QMAKE) -o project.pbxproj RavensbourneTable.pro -spec macx-xcode

qmake_all: FORCE

